import javax.swing.*;
import java.awt.Desktop;
import java.io.File;

/**
 * Main form
 */
public class MainForm extends javax.swing.JFrame {
    /**
     * Directory with gp files
     */
    private String gpDirectory;
    /**
     * Path to tmdata.xml which contain data
     */
    private String pathXml;
    /**
     * Path to the HTML help page
     */
    private String pathHtml;
    private Xml xml = new Xml();
    private final String SELECT_STRING = "Select";

    /**
     * Constructor
     */
    public MainForm() {
        initComponents();
        // Current node of the application
        File absolutePath = new File("");
        String current = absolutePath.getAbsolutePath();
        // Add data and help in the same directory as the application
        // TODO configuration file
        pathXml = current + File.separator + "TMdata.xml";
        pathHtml = current + File.separator + "help.html";
        xml.setFile(pathXml);
        // TODO handle file list case
        fileComboBox.setVisible(false);
        jLabel2.setVisible(false);
    }

    /**
     * Initialization
     * Search for data XML file or ask the user to choose the directory which should contain gp files
     *
     * @throws Exception
     */
    public void init() throws Exception {
        FilesLister filesList = new FilesLister();
        if (!filesList.lookingForFile(pathXml)) {
            showFileChooser();
        } else {
            gpDirectory = xml.getDirectory();
            xml.update();
            showMainFrame();
        }
    }

    /**
     * Configure and show file chooser
     */
    public void showFileChooser() {
        fileChooser.setSize(600, 400);
        fileChooser.setResizable(false);
        fileChooser.setVisible(true);
    }

    public void showMainFrame()
    {
        pathComboUpdate();
        comboBoxesUpdate();
        setSize(900, 700);
        setVisible(true);
    }

    /**
     * Update a combo box regarding XML
     *
     * @param _comboBox combo box to update
     * @param _tag tag to found
     */
    private void comboUpdate(JComboBox<String> _comboBox, String _tag) {
        Pile<String> pile = xml.find(_tag);
        pile.sort();
        _comboBox.removeAllItems();
        _comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{SELECT_STRING}));
        for (int i = 0; i < pile.getSize(); i++) {
            if (pile.get(i).compareTo("") != 0) {
                _comboBox.addItem(pile.get(i));
            }
        }
    }

    /**
     * Update combo1
     * Separate method from others combos (not always updated)
     */
    private void pathComboUpdate() {
        comboUpdate(pathComboBox, Xml.PATH_TAG);
    }

    /**
     * Update combo boxes
     */
    private void comboBoxesUpdate() {
        comboUpdate(fileComboBox, Xml.FILE_TAG);
        comboUpdate(nameComboBox, Xml.NAME_TAG);
        comboUpdate(authorComboBox, Xml.AUTHOR_TAG);
        comboUpdate(albumComboBox, Xml.ALBUM_TAG);
        comboUpdate(difficultyComboBox, Xml.DIFFICULTY_TAG);
        comboUpdate(masteryComboBox, Xml.MASTERY_TAG);
        comboUpdate(commentComboBox, Xml.COMMENT_TAG);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        // Labels
        String ok_string = "Ok";
        String cancel_string = "Cancel";
        String file_string = Xml.FILE_TAG;
        String name_string = Xml.NAME_TAG;
        String author_string = Xml.AUTHOR_TAG;
        String album_string = Xml.ALBUM_TAG;
        String difficulty_string = Xml.DIFFICULTY_TAG;
        String mastery_string = Xml.MASTERY_TAG;
        String comment_string = Xml.COMMENT_TAG;

        modificationFrame = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        authorTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        albumTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        difficultyTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        masteryTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        commentTextField = new javax.swing.JTextField();
        viewFrame = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        pathLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        albumLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        masteryLabel = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        commentLabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        fileChooser = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        pathComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fileComboBox = new javax.swing.JComboBox();
        nameComboBox = new javax.swing.JComboBox();
        authorComboBox = new javax.swing.JComboBox();
        albumComboBox = new javax.swing.JComboBox();
        difficultyComboBox = new javax.swing.JComboBox();
        masteryComboBox = new javax.swing.JComboBox();
        commentComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        modificationFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificationFrame.setResizable(false);
        jLabel9.setText(Xml.NAME_TAG);

        nameTextField.setText("nameTextField");
        nameTextField.setMaximumSize(new java.awt.Dimension(6, 20));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel10.setText(author_string);

        jButton3.setText(ok_string);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        jButton4.setText(cancel_string);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        authorTextField.setText("authorTextField");

        jLabel11.setText(album_string);

        albumTextField.setText("albumTextField");

        jLabel12.setText(difficulty_string);

        difficultyTextField.setText("difficultyTextField");

        jLabel13.setText(mastery_string);

        masteryTextField.setText("masteryTextField");

        jLabel14.setText(comment_string);

        commentTextField.setText("commentTextField");
        commentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(modificationFrame.getContentPane());
        modificationFrame.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel11)
                                        .add(jLabel12)
                                        .add(jLabel13)
                                        .add(jLabel14)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jFrame1Layout.createSequentialGroup()
                                                .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, masteryTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, difficultyTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, albumTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, authorTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, nameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel10)
                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel9)
                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, commentTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jButton3)
                                                .add(9, 9, 9)
                                                .add(jButton4)))
                                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel10)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(authorTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel11)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(albumTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel12)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(difficultyTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel13)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(masteryTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel14)
                                .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jFrame1Layout.createSequentialGroup()
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                                        .add(jButton3)
                                                        .add(jButton4))
                                                .addContainerGap())
                                        .add(jFrame1Layout.createSequentialGroup()
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(commentTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
        );
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setText(file_string);

        pathLabel.setText("jLabel15");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel17.setText(name_string);

        nameLabel.setText("jLabel15");

        jLabel19.setText(author_string);

        authorLabel.setText("jLabel15");

        jLabel21.setText(album_string);

        albumLabel.setText("jLabel15");

        jLabel23.setText(difficulty_string);

        difficultyLabel.setText("jLabel15");

        jLabel25.setText(mastery_string);

        masteryLabel.setText("jLabel15");

        jLabel27.setText(comment_string);

        commentLabel.setText("jlabel28");

        jButton5.setText(ok_string);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(cancel_string);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jFrame2Layout = new org.jdesktop.layout.GroupLayout(viewFrame.getContentPane());
        viewFrame.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
                jFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jFrame2Layout.createSequentialGroup()
                                .addContainerGap(251, Short.MAX_VALUE)
                                .add(jButton5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton6)
                                .addContainerGap())
                        .add(jFrame2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel27)
                                .addContainerGap(332, Short.MAX_VALUE))
                        .add(jFrame2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(commentLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                        .add(jLabel15)
                                        .add(pathLabel)
                                        .add(jLabel17)
                                        .add(jLabel19)
                                        .add(authorLabel)
                                        .add(jLabel21)
                                        .add(albumLabel)
                                        .add(difficultyLabel)
                                        .add(jLabel23)
                                        .add(jLabel25)
                                        .add(masteryLabel)
                                        .add(nameLabel))
                                .addContainerGap())
        );
        jFrame2Layout.setVerticalGroup(
                jFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jFrame2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel15)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pathLabel)
                                .add(16, 16, 16)
                                .add(jLabel17)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(nameLabel)
                                .add(14, 14, 14)
                                .add(jLabel19)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(authorLabel)
                                .add(16, 16, 16)
                                .add(jLabel21)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(albumLabel)
                                .add(16, 16, 16)
                                .add(jLabel23)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(difficultyLabel)
                                .add(17, 17, 17)
                                .add(jLabel25)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(masteryLabel)
                                .add(16, 16, 16)
                                .add(jLabel27)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(commentLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 7, Short.MAX_VALUE)
                                .add(jFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jButton6)
                                        .add(jButton5))
                                .addContainerGap())
        );
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jFrame3Layout = new org.jdesktop.layout.GroupLayout(fileChooser.getContentPane());
        fileChooser.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
                jFrame3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jFrame3Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jFileChooser1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame3Layout.setVerticalGroup(
                jFrame3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jFrame3Layout.createSequentialGroup()
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jFileChooser1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pathComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{SELECT_STRING}));
        pathComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText(ok_string);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        jButton2.setText(cancel_string);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        fileComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{SELECT_STRING}));
        fileComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileComboBoxActionPerformed(evt);
            }
        });

        nameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{SELECT_STRING}));
        nameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboBoxActionPerformed(evt);
            }
        });

        authorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{SELECT_STRING}));
        authorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorComboBoxActionPerformed(evt);
            }
        });

        albumComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{SELECT_STRING}));
        albumComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumComboBoxActionPerformed(evt);
            }
        });

        difficultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{SELECT_STRING}));
        difficultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyComboBoxActionPerformed(evt);
            }
        });

        masteryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{SELECT_STRING}));
        masteryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masteryComboBoxActionPerformed(evt);
            }
        });

        commentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{SELECT_STRING}));
        commentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText(file_string);

        jLabel2.setText("File name");

        jLabel3.setText(name_string);

        jLabel4.setText(author_string);

        jLabel5.setText(album_string);

        jLabel6.setText(difficulty_string);

        jLabel7.setText(mastery_string);

        jLabel8.setText(comment_string);

        jMenu1.setText("Menu");
        jMenuItem1.setText("Modify");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificationMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Show");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Show XML");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Help");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Quit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Update XML");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });

        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Reload search");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });

        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .add(jButton1)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(jButton2))
                                                .add(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .add(pathComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .add(fileComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .add(nameComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .add(authorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .add(albumComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .add(difficultyComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .add(masteryComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .add(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .add(jLabel1))
                                        .add(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .add(jLabel2))
                                        .add(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .add(jLabel3))
                                        .add(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .add(jLabel4))
                                        .add(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .add(jLabel5))
                                        .add(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .add(jLabel6))
                                        .add(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(commentComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                        .add(jLabel7)
                                                        .add(jLabel8))))
                                .addContainerGap(403, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .add(107, 107, 107)
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pathComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2)
                                .add(6, 6, 6)
                                .add(fileComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel3)
                                .add(6, 6, 6)
                                .add(nameComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel4)
                                .add(6, 6, 6)
                                .add(authorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel5)
                                .add(6, 6, 6)
                                .add(albumComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel6)
                                .add(6, 6, 6)
                                .add(difficultyComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel7)
                                .add(6, 6, 6)
                                .add(masteryComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel8)
                                .add(6, 6, 6)
                                .add(commentComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 47, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jButton2)
                                        .add(jButton1))
                                .addContainerGap())
        );
        pack();
    }

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {
        // User click on OK button
        if (evt.getActionCommand().equals("ApproveSelection")) {
            gpDirectory = jFileChooser1.getSelectedFile().getAbsolutePath();
            // Add the directory (absolute path) to the XML
            xml.addDirectory(gpDirectory);
            fileChooser.dispose();
            xml.load();
            showMainFrame();
        }
        else if (evt.getActionCommand().equals("CancelSelection")) {
            System.exit(0);
        }
    }

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
        pathComboUpdate();
        comboBoxesUpdate();
    }

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        viewFrame.dispose();
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        validateButtonActionPerformed(evt);
        viewFrame.dispose();
    }

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {
        xml.update();
        pathComboUpdate();
        comboBoxesUpdate();
    }

    private void menuViewActionPerformed(java.awt.event.ActionEvent evt) {
        // If something have been selected in pathComboBox
        if (pathComboBox.getSelectedItem().toString().compareTo(SELECT_STRING) != 0) {
            pathLabel.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.PATH_TAG));
            nameLabel.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.NAME_TAG));
            authorLabel.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.AUTHOR_TAG));
            albumLabel.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.ALBUM_TAG));
            difficultyLabel.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.DIFFICULTY_TAG));
            masteryLabel.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.MASTERY_TAG));
            commentLabel.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.COMMENT_TAG));
            viewFrame.setSize(700, 500);
            viewFrame.setVisible(true);
        }
    }

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            File file = new File(pathXml);
            Desktop desktop = Desktop.getDesktop();
            desktop.open(file);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            File file = new File(pathHtml);
            Desktop desktop = Desktop.getDesktop();
            desktop.open(file);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        modificationFrame.dispose();
    }

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO handle update in xml class
        xml.setElementValue(pathComboBox.getSelectedItem().toString(), Xml.NAME_TAG, nameTextField.getText());
        xml.setElementValue(pathComboBox.getSelectedItem().toString(), Xml.AUTHOR_TAG, authorTextField.getText());
        xml.setElementValue(pathComboBox.getSelectedItem().toString(), Xml.ALBUM_TAG, albumTextField.getText());
        xml.setElementValue(pathComboBox.getSelectedItem().toString(), Xml.DIFFICULTY_TAG, difficultyTextField.getText());
        xml.setElementValue(pathComboBox.getSelectedItem().toString(), Xml.MASTERY_TAG, masteryTextField.getText());
        xml.setElementValue(pathComboBox.getSelectedItem().toString(), Xml.COMMENT_TAG, commentTextField.getText());
        xml.save();
        comboBoxesUpdate();
        modificationFrame.dispose();
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void modificationMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (pathComboBox.getSelectedItem().toString().compareTo(SELECT_STRING) != 0) {
            nameTextField.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.NAME_TAG));
            authorTextField.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.AUTHOR_TAG));
            albumTextField.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.ALBUM_TAG));
            difficultyTextField.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.DIFFICULTY_TAG));
            masteryTextField.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.MASTERY_TAG));
            commentTextField.setText(xml.readElement(pathComboBox.getSelectedItem().toString(), Xml.COMMENT_TAG));
            modificationFrame.setSize(400, 400);
            modificationFrame.setVisible(true);
        }
    }

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            File file = new File(pathComboBox.getSelectedItem().toString());
            Desktop desktop = Desktop.getDesktop();
            desktop.open(file);

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * Select path in pathComboBox that corresponding to the selection of _comboBox
     *
     * @param _comboBox JComboBox<String>
     * @param _tag String
     */
    private void comboBoxAction(JComboBox<String> _comboBox, String _tag) {
        if (_comboBox.getItemCount() > 0) {
            if (_comboBox.getSelectedItem().toString().compareTo(SELECT_STRING) != 0) {
                pathComboBox.removeAllItems();
                Pile<String> list = xml.findPath(_tag, _comboBox.getSelectedItem().toString());
                for (int i = 0; i < list.getSize(); i++) {
                    pathComboBox.addItem(list.get(i));
                }
            }
        }
    }

    private void commentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        comboBoxAction(commentComboBox, Xml.COMMENT_TAG);
    }

    private void masteryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        comboBoxAction(masteryComboBox, Xml.MASTERY_TAG);
    }

    private void difficultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        comboBoxAction(difficultyComboBox, Xml.DIFFICULTY_TAG);
    }

    private void albumComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        comboBoxAction(albumComboBox, Xml.ALBUM_TAG);
    }

    private void authorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        comboBoxAction(authorComboBox, Xml.AUTHOR_TAG);
    }

    private void nameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        comboBoxAction(nameComboBox, Xml.NAME_TAG);
    }

    private void fileComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Exit the application
        System.exit(0);
    }

    private void pathComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox <String> pathComboBox;
    private javax.swing.JComboBox <String> fileComboBox;
    private javax.swing.JComboBox <String> nameComboBox;
    private javax.swing.JComboBox <String> authorComboBox;
    private javax.swing.JComboBox <String> albumComboBox;
    private javax.swing.JComboBox <String> difficultyComboBox;
    private javax.swing.JComboBox <String> masteryComboBox;
    private javax.swing.JComboBox <String> commentComboBox;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame modificationFrame;
    private javax.swing.JFrame viewFrame;
    private javax.swing.JFrame fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel albumLabel;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel masteryLabel;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JTextField albumTextField;
    private javax.swing.JTextField difficultyTextField;
    private javax.swing.JTextField masteryTextField;
    private javax.swing.JTextField commentTextField;
    // End of variables declaration
}
